services:
  eth-node:
    build: ./EthNode.Dockerfile
  chainlink-node:
    build: ./ChainlinkNode.Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
