name: CI checks and codecov

on:
  push:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C link-dead-code"

jobs:
  call_codecov_workflow:
    uses: banyancomputer/.github/.github/workflows/rust-codecov.yml@master
  run_linters:
    uses: banyancomputer/.github/.github/workflows/rust_linters_formatters.yml@master
  run_tests:
    uses: banyancomputer/.github/.github/workflows/rust_test.yml@master
  run_todo:
    uses: banyancomputer/.github/.github/workflows/todo.yml@master
